config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'dashboard/create_todo'
  post 'dashboard/do_create_todo'
  delete 'dashboard/destroy_todo'
  get 'dashboard/toggle_completed'
  get 'dashboard/assign_user'
  get 'sessions/register'
  post 'sessions/do_register'
  resources :user_todo_lists
  resources :todos
  resources :todo_lists
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_todo, only: [:toggle_completed, :destroy_todo]
  def index
    @todos = []
    return unless params[:list_id]

    @todo_list = current_user.todo_lists.where(id: params[:list_id]).first
    @todos = @todo_list.todos if @todo_list
  end

  def create_todo
  end

  def do_create_todo
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.js
      else
        format.js do
          flash.now[:danger] = @todo.errors.full_messages
          render partial: 'shared/flash_renderer', status: :unprocessable_entity
        end
      end
    end
  end

  def destroy_todo
    @todo.destroy
  end

  def toggle_completed
    @todo.update_attribute(:completed, !@todo.completed)
  end

  def assign_user
    session[:current_user_id] = params[:user_id] if params[:user_id]
    redirect_to dashboard_index_path
  end

  private

  def todo_params
    params.require(:todo).permit(:content, :todo_list_id)
  end

  def set_todo
    todo_list = current_user.todo_lists.find(params[:list_id])
    @todo = todo_list.todos.find(params[:todo_id])
  end
end

app/views/dashboard/_create_todo_form.html.erb
<%= form_with(model: Todo.new, url: dashboard_do_create_todo_path, remote: true) do |form| %>
  <%= form.hidden_field :todo_list_id, value: list_id %>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_field :content, class: 'form-control', required: true %>
  </div>

  <div class="actions">
    <%= form.submit 'Create', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/dashboard/_todo.html.erb
<%= content_tag :li, class: 'list-group-item list-group-item-action list-group-item-light border-0 my-2 ml-1', data: {'todo-id': todo.id} do %>
  <div class="d-flex">
    <%= link_to dashboard_toggle_completed_path(list_id: list_id, todo_id: todo.id), class: 'mr-2', remote: true do %>
      <% if todo.completed? %>
        <%= faw_icon 'solid', 'check-square', { extra_class: 'ttd-svg-success', size: '2x' } %>
      <% else %>
        <%= faw_icon 'regular', 'square', { extra_class: 'ttd-svg-secondary', size: '2x' } %>
      <% end %>
    <% end %>

    <% if todo.completed? %>
      <del class="font-weight-bold pt-1"><%= todo.content %></del>
    <% else %>
      <span class="text-dark font-weight-bold pt-1">
        <%= todo.content %>
      </span>
    <% end %>

    <%= link_to dashboard_destroy_todo_path(list_id: list_id, todo_id: todo.id), class: 'ml-auto ttd-button-hide', remote: true, data: {method: :delete} do %>
      <%= faw_icon 'light', 'trash-alt', { extra_class: 'ttd-svg-primary', size: '2x' } %>
    <% end %>
  </div>
<% end %>

app/views/dashboard/_todo_list.html.erb
<%= link_to dashboard_index_path(list_id: todo_list.id), class: "list-group-item list-group-item-action list-group-item-light border-0 #{active_tl(todo_list.id) ? 'ttd-todo-list-selected' : ''}" do %>
  <%= faw_icon 'light', 'list', { extra_class: 'mr-2' } %>
  <span class="text-dark font-weight-bold">
    <%= todo_list.label %>
  </span>
<% end %>

app/views/dashboard/create_todo.js.erb
var ttdCreateTodoModal = $("#ttd-create-todo-modal");

ttdCreateTodoModal
    .find(".ttd-create-todo-modal-form")
    .html("<%= j render partial: 'dashboard/create_todo_form', locals: { list_id: params[:list_id] } %>");

ttdCreateTodoModal.modal();

app/views/dashboard/destroy_todo.js.erb
var todo = $('#todos [data-todo-id="<%= params[:todo_id] %>"]');

if (todo.length) {
    todo.remove();
}

app/views/dashboard/do_create_todo.js.erb
var todo = $('#todos [data-todo-id="<%= params[:todo_id] %>"]');
var ttdCreateTodoModal = $("#ttd-create-todo-modal");

ttdCreateTodoModal
    .find(".ttd-create-todo-modal-form input[type=text]").val('');

if (todo.length) {
    todo.replaceWith("<%= j render partial: 'dashboard/todo', locals: { todo: @todo, list_id: @todo.todo_list_id } %>");
} else {
    $('#todos').append("<%= j render partial: 'dashboard/todo', locals: { todo: @todo, list_id: @todo.todo_list_id } %>");
}

app/views/dashboard/index.html.erb
<div class="row mb-3">
  <div class="col-4 pt-2">
    <div class="media">
      <%= image_tag current_user.avatar, class: 'align-self-center mr-3 rounded-circle',  size: "47x47"  %>
      <div class="media-body">
        <h5 class="mt-2 text-dark"><%= current_user.full_name %></h5>
      </div>
    </div>

    <div class="list-group mt-5">
      <% if current_user.todo_lists.any? %>
        <%= render partial: 'dashboard/todo_list', collection: current_user.todo_lists.order(created_at: :ASC) %>
      <% end %>
    </div>
  </div>

  <div class="col-6 ttd-box-shadow p-0 pl-1">
    <div class="position-relative">
      <%= image_tag 'rocks_m.jpg', class: 'img-fluid' %>
      <div class="title-holder">
        <h4><%= @todo_list.label if @todo_list %></h4>
        <p><%= Time.current.strftime('%a %d %B') %></p>
      </div>
    </div>

    <ul class="list-group mt-2" id="todos">
      <% if @todos.any? %>
        <%= render partial: 'dashboard/todo', collection: @todos.order(created_at: :ASC), locals: { list_id: params[:list_id] } %>
      <% end %>
    </ul>

    <div class="ttd-bg-grey pb-5 pt-2 pl-3">
      <% if @todo_list %>
        <%= link_to dashboard_create_todo_path(list_id: params[:list_id]), class: 'font-weight-bold text-decoration-none', remote: true do %>
          <%= faw_icon 'solid', 'plus-circle', { extra_class: 'ttd-svg-primary float-left', size: '2x' }  %>
          <div class="float-left mt-1 ml-2">Add a to-do</div>
        <% end %>
      <% end %>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

app/views/dashboard/toggle_completed.js.erb
var todo = $('#todos [data-todo-id="<%= params[:todo_id] %>"]');

if (todo.length) {
    todo.replaceWith("<%= j render partial: 'dashboard/todo', locals: { todo: @todo, list_id: @todo.todo_list_id } %>");
}