config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get 'dashboard/create_todo'
  post 'dashboard/do_create_todo'
  delete 'dashboard/destroy_todo'
  get 'dashboard/toggle_completed'
  get 'dashboard/assign_user'
  get 'sessions/register'
  post 'sessions/do_register'
  resources :user_todo_lists
  resources :todos
  resources :todo_lists
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_todo_list.rb
class UserTodoList < ApplicationRecord
  belongs_to :user
  belongs_to :todo_list
end

app/controllers/user_todo_lists_controller.rb
class UserTodoListsController < ApplicationController
  before_action :set_user_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /user_todo_lists
  # GET /user_todo_lists.json
  def index
    @user_todo_lists = UserTodoList.all
  end

  # GET /user_todo_lists/1
  # GET /user_todo_lists/1.json
  def show
  end

  # GET /user_todo_lists/new
  def new
    @user_todo_list = UserTodoList.new
  end

  # GET /user_todo_lists/1/edit
  def edit
  end

  # POST /user_todo_lists
  # POST /user_todo_lists.json
  def create
    @user_todo_list = UserTodoList.new(user_todo_list_params)

    respond_to do |format|
      if @user_todo_list.save
        format.html { redirect_to @user_todo_list, notice: 'User todo list was successfully created.' }
        format.json { render :show, status: :created, location: @user_todo_list }
      else
        format.html { render :new }
        format.json { render json: @user_todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_todo_lists/1
  # PATCH/PUT /user_todo_lists/1.json
  def update
    respond_to do |format|
      if @user_todo_list.update(user_todo_list_params)
        format.html { redirect_to @user_todo_list, notice: 'User todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_todo_list }
      else
        format.html { render :edit }
        format.json { render json: @user_todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_todo_lists/1
  # DELETE /user_todo_lists/1.json
  def destroy
    @user_todo_list.destroy
    respond_to do |format|
      format.html { redirect_to user_todo_lists_url, notice: 'User todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_todo_list
      @user_todo_list = UserTodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_todo_list_params
      params.require(:user_todo_list).permit(:user_id, :todo_list_id)
    end
end

app/views/user_todo_lists/_form.html.erb
<%= form_with(model: user_todo_list, local: true) do |form| %>
  <% if user_todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_todo_list.errors.count, "error") %> prohibited this user_todo_list from being saved:</h2>

      <ul>
        <% user_todo_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.collection_select(:user_id, User.all, :id, :full_name, {include_blank: true}, {'data-placeholder': 'Please select...'}) %>
  </div>

  <div class="form-group">
    <%= form.label :todo_list_id %>
    <%= form.collection_select(:todo_list_id, TodoList.all, :id, :label, {include_blank: true}, {'data-placeholder': 'Please select...'}) %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/user_todo_lists/edit.html.erb
<h1>Editing User Todo List</h1>

<%= render 'form', user_todo_list: @user_todo_list %>

<%= link_to 'Show', @user_todo_list %> |
<%= link_to 'Back', user_todo_lists_path %>

app/views/user_todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Todo Lists</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Todo list</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_todo_lists.each do |user_todo_list| %>
      <tr>
        <td><%= user_todo_list.user_id %></td>
        <td><%= user_todo_list.todo_list_id %></td>
        <td><%= link_to 'Show', user_todo_list %></td>
        <td><%= link_to 'Edit', edit_user_todo_list_path(user_todo_list) %></td>
        <td><%= link_to 'Destroy', user_todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Todo List', new_user_todo_list_path %>

app/views/user_todo_lists/new.html.erb
<h1>New User Todo List</h1>

<%= render 'form', user_todo_list: @user_todo_list %>

<%= link_to 'Back', user_todo_lists_path %>

app/views/user_todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_todo_list.user_id %>
</p>

<p>
  <strong>Todo list:</strong>
  <%= @user_todo_list.todo_list_id %>
</p>

<%= link_to 'Edit', edit_user_todo_list_path(@user_todo_list) %> |
<%= link_to 'Back', user_todo_lists_path %>